### ISSUE TITLE
Visible and Minimized

### ISSUE THREAD

**Issue by Nick74k** [TurboPack/RibbonFramework#70] opened 2017-10-20 07:24 UTC
Setting ribbon.visible := true also internally resets ribbon.minimized to false.
I can set it again to minimized after setting visible, but it causes flickering of ribbon - first it draws maximized and then switched to minimized.
```
procedure TForm5.FormCreate(Sender: TObject);
begin
  Ribbon.Visible := false;
  Ribbon.Minimized := true;
end;

procedure TForm5.Button1Click(Sender: TObject);
begin
  Ribbon.Visible := true;
  Ribbon.Minimized := true; // Without this ribbon will not be minimized, but now it causes flickering!!!
end;

```

Also setting of ribbon.visible := false at form.OnShow hides ribbon, but window header then showed with black color. Not a problem - I can move it to OnCreate, but it is not obvious.
```
procedure TForm5.FormShow(Sender: TObject);
begin
  Ribbon.Visible := false; // Now window header will be black
end;
```

**Comment by Nick74k** [comment] 2017-10-20 10:36
Moved second part to issue #74 - it is not connected with OnShow, it always redraws window header.

**Comment by SaschaSchaefer** [comment] 2017-10-20 14:37
Cannot be reproduced anymore. Possibly fixed by the changes that were made for issue 74. Could you please test again and check if this still occurs?

**Comment by Nick74k** [comment] 2017-10-23 06:34
Now ribbon shows minimized, but with black color. See example project and screenshot.

[RibTest.zip](https://github.com/TurboPack/RibbonFramework/files/1405966/RibTest.zip)
![2017-10-23_9-31-40 988](https://user-images.githubusercontent.com/18185040/31875085-3d19d92c-b7d5-11e7-94fd-b1f4c201a861.jpg)

**Comment by Nick74k** [comment] 2017-10-23 07:12
Second project - ribbon set as minimized at OnCreate, but showed maximized after button click.

[RibTest.zip](https://github.com/TurboPack/RibbonFramework/files/1406050/RibTest.zip)

**Comment by SaschaSchaefer** [comment] 2017-10-23 09:21
Okay, with the sample projects I can reproduce it. 

The reason that the ribbon is shown maximized, if Minimized is set to true in OnCreate, is that the ribbon is not yet initialized. You should move calls like that to the "OnLoaded" event of the ribbon.

A bit more problematic is the black bar, where the ribbon is supposed to be. This occurs when the ribbon is minimalized, without it ever having been visible before.
Even if both 
  ```
  Ribbon.Minimized := true;
  Ribbon.Visible := false;
```
are moved to OnLoaded, we still get the black bar. I think the framework cannot handle setting the ribbon to minimized, without it having been drawn already, once before. 

I don't think there is much we can do to fix this. This seems to be caused by the framework itself, not by the Delphi wrapper...
To work around this, you would have to ensure that the ribbon has processed a paint message, before calling Visible := False. This code, for example would work:

  ```
procedure TForm5.RibbonLoaded(Sender: TObject);
begin
    Ribbon.Minimized := true;
    Application.ProcessMessages;
    Ribbon.Visible := False;
end;
```

**Comment by Nick74k** [comment] 2017-10-23 11:32
Ok, I see. Is it possible to add Application.ProcessMessages to SetMinimized function to suppress this error?

**Comment by joachimmarder** [comment] 2017-10-23 13:21
> The reason that the ribbon is shown maximized, if Minimized is set to true in OnCreate, is that the ribbon is not yet initialized. You should move calls like that to the "OnLoaded" event of the ribbon.

Would it be possible to save this information in a member variable?

**Comment by SaschaSchaefer** [comment] 2017-10-24 07:30
>Would it be possible to save this information in a member variable?

I have added a new enum TUIRibbonState, which is now used to mark the time that the first paint message was processed by the ribbon. The call to "Minimize" will be postponed until the first paint message has been handled. This should fix this problem. Thx @joachimmarder for the suggestion!

**Closed by SaschaSchaefer** 2017-10-24 07:30 UTC
Labels: bug
