### ISSUE TITLE
Recent Items - Random access violation on child form close

### ISSUE THREAD

**Issue by karooma** [TurboPack/RibbonFramework#48] opened 2016-07-19 10:15 UTC
Hi,

I have an MDI form with a number of MDI child. I want to the file name associated with the child form before the form is closed. I put the code to add the recent item in the child form OnCloseQuery event handler. I am getting random access violation and memory leaks either when closing the main form or any of the child forms. I pinned down the problem to FRecentItems field that was nil when calling AddtorecentItems TUIRibbon method.

For the time being I wrapped the  AddtorecentItems call in a try except block.

Any ideas how can I fix this problem.

Many thanks.
![app-accessviolation-on formclose query](https://cloud.githubusercontent.com/assets/20535050/16946563/1dd3ff32-4da2-11e6-8093-26e4a4173743.png)
![app-memory leaks](https://cloud.githubusercontent.com/assets/20535050/16946564/1dd668a8-4da2-11e6-9d6f-61528fa40a17.png)

**Comment by joachimmarder** [comment] 2016-07-19 20:47
> I want to the file name associated with the child form before the form is closed.
> I put the code to add the recent item in the child form OnCloseQuery event handler

What sense does it make to add a file path to the recent items of a ribbon control that is about to be destroyed? The ribbon control will never have the ability to show this new path in the recent irems.

> I am getting random access violation

Please post at least the full call stack of the exception, the screenshot won't help tracking down the problem. Even better would be an error report generated by EurekaLog or MadExcept. Or even better a sample project that allows to replicate the problem. This may be based on one of the included demo projects.

> Any ideas how can I fix this problem.

Please note that this is a bug tracker, not a support forum and follow the guidelines for submitting bugs on the project start page.

**Comment by karooma** [comment] 2016-07-20 10:05
The recent path is added upon closing the child form not the main form. So it does make sense. As I said, the problem is that FRecentItems was not assigned when calling AddToRecentItems. 

Below is the call stack screenshot. I will have a test case ready asap.
![2016-07-20_11-02-32](https://cloud.githubusercontent.com/assets/20535050/16982788/c6d3b740-4e69-11e6-9fab-b51ccc9c97c1.png)

**Comment by joachimmarder** [comment] 2016-07-20 15:34
I think I know what caused this AV, it should hopefully be fixed in GitHub master and next V2.2.1.

**Comment by karooma** [comment] 2016-07-20 15:39
Excellent new. any ETA.

**Comment by joachimmarder** [comment] 2016-07-20 17:08
> any ETA.

GitHub master can be downloaded at any time as ZIP file. V2.2.1 will follow shortly.

**Comment by karooma** [comment] 2016-07-20 21:48
Still having the same AV.

**Comment by karooma** [comment] 2016-07-21 20:11
Please reopen this issue, seems not fixed yet.

**Comment by joachimmarder** [comment] 2016-07-21 20:29
> Still having the same AV.

Any chance that you provide a sample project?

**Comment by karooma** [comment] 2016-07-21 20:56
I think it is the best way to solve this issue. I'll get back to you with a minimal project and more details.

**Comment by joachimmarder** [comment] 2016-07-28 13:14
> I'll get back to you with a minimal project and more details. 

Have you been able to reproduce this in a sample project?

**Comment by karooma** [comment] 2016-07-28 15:10
Not yet. I'll get back to you asap on this and other issues.

Cheers.

**Comment by karooma** [comment] 2016-07-28 18:34
Here you go.
Please note also that although a command was added to the quick access toolbar, it does not show. Probably another random bug.

The project is created with delphi 10.1 berlin.

[TestFiles.zip](https://github.com/TurboPack/RibbonFramework/files/389110/TestFiles.zip)

**Comment by karooma** [comment] 2016-07-28 18:37
l

**Comment by karooma** [comment] 2016-07-28 18:38
hghhgg

**Comment by joachimmarder** [comment] 2016-07-28 19:18
Thanks for the sample project. 

What I found out is that the Windows Ribbon Framework initializes the Recent Items (including firing the `CreateUICommand` event) when the backstage menu is opened the first. So until then, the member `fRecentItems` is simply not assigned.

I guess no one recognized this earlier because typically the action to open a file is part of the backstage menu, and typically only files that had been opened are added to the recent items (like in TextPad sample project).

If you open the backstage menu once, the exception does not occur.

Proposed solution:
  * Add `TUIRibbon.GetRecentItems()` as protected lazy getter for `fRecentITems: TUICommandRecentItems`
  * In `TUIRibbon.OnCreateUICommand()` create `TUICommandRecentItems` only in case `fRecentItems` is not assigned.

**Comment by karooma** [comment] 2016-07-28 20:02
Please go ahead.

**Comment by karooma** [comment] 2016-09-02 10:20
Any chance to have the fix in the coming days, 

thanks.

**Comment by joachimmarder** [comment] 2016-09-04 12:04
The issue is fixed in GitHub master.

**Closed by joachimmarder** 2016-09-04 12:04 UTC
Labels: bug

**Comment by karooma** [comment] 2016-09-04 13:35
Hi,
Seems that the changes are still not effected in the master branch as last activity was on Jul 28th. Can you please check it out.

**Comment by joachimmarder** [comment] 2016-09-04 19:47
> Seems that the changes are still not effected in the master branch

This was the commit: https://github.com/TurboPack/RibbonFramework/commit/66d6747e493888d07ac24eea5fe0665cccc5992e

I don't see an AV with your original demo project any more.
