### ISSUE TITLE
Font Controls Cause Access Violation when Applying Vcl Styles

### ISSUE THREAD

**Issue by richardzarr** [TurboPack/RibbonFramework#96] opened 2018-07-19 21:42 UTC
[Ribbon Test.zip](https://github.com/TurboPack/RibbonFramework/files/2211733/Ribbon.Test.zip)

Unzip and compile the attached project (derived from one of the included demos)... run and follow these steps:
1. Application defaults to Windows style - hover over the font and font size drop down boxes in the font control on the ribbon... no effect, works fine.  Can drop down and view all installed fonts, etc.
2. Click the "Carbon" button which applies the "carbon" Vcl style.  Ribbon works fine except when you hover over the font or font size drop down boxes it produces an access violation.  There are also issues with Galleries, but I have not investigated why yet... similar issue.
3. Click the "Windows" button and the style returns to the system default.  The font controls now work again properly without creating an AV.
4. Any other style except the default windows style produces the AV as stated.

**Comment by joachimmarder** [comment] 2018-07-20 07:49
This is a duplicate of #86.

**Closed by joachimmarder** 2018-07-20 07:49 UTC
Labels: duplicate
